name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: bikram73

          # Base sections (important)
          base: header, activity, community, repositories

          # Template
          template: classic

          # REQUIRED for all-time contributions
          plugin_activity: yes
          plugin_activity_limit: 0
          plugin_activity_days: 0
          plugin_activity_filter: all

          # REQUIRED for repositories with contributions
          plugin_repositories: yes

          # Lines of code changed
          plugin_lines: yes
          plugin_lines_sections: base
